#!/usr/bin/env bash

[[ -z "$1" ]] && exit 1

if [[ -d "vim/bundle/$1" ]]; then
    git submodule deinit -f "vim/bundle/$1"
else
    printf '%s\n' "Couldn't run 'git submodule deinit vim/bundle/$1', does not exist" >&2
    exit 1
fi

if [[ -d "vim/bundle/$1" ]]; then
    git rm -f "vim/bundle/$1"
else
    printf '%s\n' "Couldn't run 'git rm vim/bundle/$1', does not exist" >&2
    exit 1
fi

if [[ -d ".git/modules/vim/bundle/$1" ]]; then
    rm -rf ".git/modules/vim/bundle/$1"
else
    printf '%s\n' "Couldn't run 'rm -rf .git/modules/vim/bundle/$1', does not exist" >&2
    exit 1
fi
