#!/usr/bin/env bash

[[ -z $1 ]] && exit 1

[[ -d "vim/bundle/${1}" ]] && git submodule deinit -f $2 "vim/bundle/${1}" || echo "Couldn't run 'git submodule deinit $2 vim/bundle/${1}', $1 does not exist"
[[ -d "vim/bundle/${1}" ]] && git rm "vim/bundle/${1}" || echo "Couldn't run 'git rm vim/bundle/${1}', vim/bundle/${1} does not exist"
[[ -d "${PWD}/.git/modules/vim/bundle/${1}" ]] && rm -rf "${PWD}/.git/modules/vim/bundle/${1}" || echo "Couldn't run 'rm -rf ${PWD}/.git/modules/vim/bundle/${1}', ${PWD}/.git/modules/vim/bundle/${1} does not exist"
