#!/usr/bin/env bash

cd "${0%/*}"

git pull origin
git submodule update --init --recursive

if [ $(cat .git/modules/vim/bundle/vim-coloresque/HEAD | grep -c 0c21b1469993e610600e88e734ffe90b9c10a514) = 1 ]; then
    git checkout -- vim/bundle/vim-coloresque
    git rm --cached vim/bundle/vim-coloresque
fi

[[ -f .gitmodules ]] && for each in vim/bundle/*; do
    if [ -d "$each" ]; then
        if [ -f "${each}/.git" ]; then
            FILE=$(echo $each | grep -o -e "[^\/]*$")
           [[ `cat .gitmodules | grep "path = " |  grep -o -e "[^\/]*$" | grep -c "${FILE}"` = 0 ]] && (rm -rf "${each}" && echo "Deleted: ${each}" || (echo -e "\033[01;31mWARNING\033[00m: '${each}' was removed upstream but couldn't be deleted here.\n\nPlease delete ${each} manually."; exit 1))
        fi
    fi
done
exit 0
